import json
import time
from pathlib import Path

from tools.data_loader import load_problem_data
from tools.battery import EVParameters
from tools.objective import ObjectiveWeights
from algorithms.simmulated_annealing import simulated_annealing
from algorithms.genetic_algorithm import genetic_algorithm
from algorithms.ant_colony import ant_colony_optimization
from algorithms.greedy import greedy_nearest_neighbor
from tools.compare import run_controlled_comparison, print_detailed_metrics
from tools.statistics import pairwise_wilcoxon, print_wilcoxon_table, print_summary_table, to_latex_table
from tools.plot import (
    plot_convergence,
    plot_convergence_by_evaluations,
    plot_box_comparison,
    plot_sa_diagnostics,
    plot_ga_diagnostics,
    plot_aco_diagnostics,
    plot_cost_breakdown,
    plot_runtime_comparison,
    print_comparison_table,
)

# ── Instance selection ────────────────────────────────────────────────────────
# Change INSTANCE to switch between problem instances.
# Each instance lives in EV_routing/instances/<name>/ and outputs go to
# EV_routing/results/<name>/ — everything is kept separate per instance.
INSTANCE      = "sf_75"
INSTANCE_DIR  = Path(f"EV_routing/instances/{INSTANCE}")
RESULTS_DIR   = Path(f"EV_routing/results/{INSTANCE}")
FIGURES_DIR   = RESULTS_DIR / "figures"
PARAMS_FILE   = RESULTS_DIR / "params.json"
# ─────────────────────────────────────────────────────────────────────────────

SEEDS      = list(range(10))
MAX_EVALS  = 150_000   # shared evaluation budget for all algorithms


def main() -> None:
    # ------------------------------------------------------------------
    # Problem setup
    # ------------------------------------------------------------------
    ev_params = EVParameters(
        battery_capacity_kwh=20.0,
        initial_battery_kwh=20.0,
        energy_consumption_kwh_per_km=0.50,
        average_speed_kmh=50.0,
        grade_factor=3.0,
        speed_exponent=2.0,
    )

    data = load_problem_data(INSTANCE_DIR, ev_params)

    # Load calibrated weights from weights.json (generated by scripts/calibrate_weights.py).
    # Fall back to hand-picked defaults if the file doesn't exist yet.
    _weights_file = RESULTS_DIR / "weights.json"
    if _weights_file.exists():
        _w = json.loads(_weights_file.read_text())["weights"]
        weights = ObjectiveWeights(**_w)
        print(f"Weights loaded from {_weights_file}")
    else:
        print("No weights.json found — using defaults. Run scripts/calibrate_weights.py first.")
        weights = ObjectiveWeights(
            distance_weight=1.0,
            travel_time_weight=10.0,
            energy_weight=2.0,
            charging_cost_weight=20.0,
            battery_violation_weight=10000.0,
            infeasible_visit_weight=5000.0,
        )

    # ------------------------------------------------------------------
    # Parameters — loaded from params.json (run scripts/tune.py to update)
    # ------------------------------------------------------------------
    if not PARAMS_FILE.exists():
        raise FileNotFoundError(
            f"No params.json found at {PARAMS_FILE}. "
            "Run: PYTHONPATH=EV_routing python EV_routing/scripts/tune.py"
        )
    with open(PARAMS_FILE) as _f:
        _p = json.load(_f)

    sa_kwargs  = _p["SA"]
    ga_kwargs  = _p["GA"]
    ma_kwargs  = _p["MA"]
    aco_kwargs = _p["ACO"]

    # ------------------------------------------------------------------
    # Single diagnostic run (SA)
    # ------------------------------------------------------------------
    print("=" * 60)
    print("Single SA run — diagnostics")
    print("=" * 60)
    t0 = time.perf_counter()
    _, best_ev, sa_stats = simulated_annealing(data=data, ev_params=ev_params, weights=weights,
                                                max_evaluations=MAX_EVALS, **sa_kwargs)
    sa_single_time = time.perf_counter() - t0

    print(f"  Feasible:            {best_ev.feasible}")
    print(f"  Objective:           {best_ev.objective_value:.4f}")
    print(f"  Distance (km):       {best_ev.total_distance_km:.2f}")
    print(f"  Travel time (h):     {best_ev.total_travel_time_h:.2f}")
    print(f"  Charging time (h):   {best_ev.total_charging_time_h:.2f}")
    print(f"  Energy (kWh):        {best_ev.total_energy_consumed_kwh:.2f}")
    print(f"  Charging cost ($):   {best_ev.total_charging_cost_usd:.2f}")
    print(f"  Battery violation:   {best_ev.battery_violation_kwh:.4f}")
    print(f"  Infeasible visits:   {best_ev.infeasible_visits}")
    print(f"  Evaluations:         {sa_stats.total_evaluated:,}")
    print(f"  Acceptance rate:     {sa_stats.acceptance_rate:.2%}")
    print(f"  Feasibility rate:    {sa_stats.feasibility_rate:.2%}")
    print(f"  Reheats:             {sa_stats.reheat_count}")
    print(f"  Runtime:             {sa_single_time:.2f}s")
    print()

    # ------------------------------------------------------------------
    # Single diagnostic run (GA)
    # ------------------------------------------------------------------
    print("=" * 60)
    print("Single GA run — diagnostics")
    print("=" * 60)
    t0 = time.perf_counter()
    _, best_ev_ga, ga_stats = genetic_algorithm(data=data, ev_params=ev_params, weights=weights,
                                                max_evaluations=MAX_EVALS, **ga_kwargs)
    ga_single_time = time.perf_counter() - t0

    print(f"  Feasible:            {best_ev_ga.feasible}")
    print(f"  Objective:           {best_ev_ga.objective_value:.4f}")
    print(f"  Distance (km):       {best_ev_ga.total_distance_km:.2f}")
    print(f"  Travel time (h):     {best_ev_ga.total_travel_time_h:.2f}")
    print(f"  Charging time (h):   {best_ev_ga.total_charging_time_h:.2f}")
    print(f"  Energy (kWh):        {best_ev_ga.total_energy_consumed_kwh:.2f}")
    print(f"  Charging cost ($):   {best_ev_ga.total_charging_cost_usd:.2f}")
    print(f"  Battery violation:   {best_ev_ga.battery_violation_kwh:.4f}")
    print(f"  Infeasible visits:   {best_ev_ga.infeasible_visits}")
    print(f"  Evaluations:         {ga_stats.total_evaluated:,}")
    print(f"  Generations:         {ga_stats.total_generations:,}")
    print(f"  Feasibility rate:    {ga_stats.feasibility_rate:.2%}")
    print(f"  Runtime:             {ga_single_time:.2f}s")
    print()

    # ------------------------------------------------------------------
    # Single diagnostic run (MA)
    # ------------------------------------------------------------------
    print("=" * 60)
    print("Single MA run — diagnostics")
    print("=" * 60)
    t0 = time.perf_counter()
    _, best_ev_ma, ma_stats = genetic_algorithm(data=data, ev_params=ev_params, weights=weights,
                                                max_evaluations=MAX_EVALS, **ma_kwargs)
    ma_single_time = time.perf_counter() - t0

    print(f"  Feasible:            {best_ev_ma.feasible}")
    print(f"  Objective:           {best_ev_ma.objective_value:.4f}")
    print(f"  Distance (km):       {best_ev_ma.total_distance_km:.2f}")
    print(f"  Travel time (h):     {best_ev_ma.total_travel_time_h:.2f}")
    print(f"  Charging time (h):   {best_ev_ma.total_charging_time_h:.2f}")
    print(f"  Energy (kWh):        {best_ev_ma.total_energy_consumed_kwh:.2f}")
    print(f"  Charging cost ($):   {best_ev_ma.total_charging_cost_usd:.2f}")
    print(f"  Battery violation:   {best_ev_ma.battery_violation_kwh:.4f}")
    print(f"  Infeasible visits:   {best_ev_ma.infeasible_visits}")
    print(f"  Evaluations:         {ma_stats.total_evaluated:,}")
    print(f"  Generations:         {ma_stats.total_generations:,}")
    print(f"  Feasibility rate:    {ma_stats.feasibility_rate:.2%}")
    print(f"  Runtime:             {ma_single_time:.2f}s")
    print()

    # ------------------------------------------------------------------
    # Single diagnostic run (ACO)
    # ------------------------------------------------------------------
    print("=" * 60)
    print("Single ACO run — diagnostics")
    print("=" * 60)
    t0 = time.perf_counter()
    _, best_ev_aco, aco_stats = ant_colony_optimization(data=data, ev_params=ev_params, weights=weights,
                                                         max_evaluations=MAX_EVALS, **aco_kwargs)
    aco_single_time = time.perf_counter() - t0

    print(f"  Feasible:            {best_ev_aco.feasible}")
    print(f"  Objective:           {best_ev_aco.objective_value:.4f}")
    print(f"  Distance (km):       {best_ev_aco.total_distance_km:.2f}")
    print(f"  Travel time (h):     {best_ev_aco.total_travel_time_h:.2f}")
    print(f"  Charging time (h):   {best_ev_aco.total_charging_time_h:.2f}")
    print(f"  Energy (kWh):        {best_ev_aco.total_energy_consumed_kwh:.2f}")
    print(f"  Charging cost ($):   {best_ev_aco.total_charging_cost_usd:.2f}")
    print(f"  Battery violation:   {best_ev_aco.battery_violation_kwh:.4f}")
    print(f"  Infeasible visits:   {best_ev_aco.infeasible_visits}")
    print(f"  Evaluations:         {aco_stats.total_evaluated:,}")
    print(f"  Iterations:          {aco_stats.total_iterations:,}")
    print(f"  Feasibility rate:    {aco_stats.feasibility_rate:.2%}")
    print(f"  Runtime:             {aco_single_time:.2f}s")
    print()

    # ------------------------------------------------------------------
    # Single diagnostic run (Greedy baseline — deterministic)
    # ------------------------------------------------------------------
    print("=" * 60)
    print("Single Greedy run — baseline")
    print("=" * 60)
    t0 = time.perf_counter()
    _, best_ev_greedy, _ = greedy_nearest_neighbor(data=data, ev_params=ev_params, weights=weights)
    greedy_single_time = time.perf_counter() - t0

    print(f"  Feasible:            {best_ev_greedy.feasible}")
    print(f"  Objective:           {best_ev_greedy.objective_value:.4f}")
    print(f"  Distance (km):       {best_ev_greedy.total_distance_km:.2f}")
    print(f"  Travel time (h):     {best_ev_greedy.total_travel_time_h:.2f}")
    print(f"  Charging time (h):   {best_ev_greedy.total_charging_time_h:.2f}")
    print(f"  Energy (kWh):        {best_ev_greedy.total_energy_consumed_kwh:.2f}")
    print(f"  Charging cost ($):   {best_ev_greedy.total_charging_cost_usd:.2f}")
    print(f"  Battery violation:   {best_ev_greedy.battery_violation_kwh:.4f}")
    print(f"  Infeasible visits:   {best_ev_greedy.infeasible_visits}")
    print(f"  Runtime:             {greedy_single_time:.2f}s")
    print()

    # ------------------------------------------------------------------
    # Controlled multi-seed comparison  (Greedy vs SA vs GA vs MA vs ACO)
    # ------------------------------------------------------------------
    print("=" * 60)
    print(f"Controlled comparison — {len(SEEDS)} seeds, budget={MAX_EVALS:,} evals")
    print("=" * 60)

    all_results = run_controlled_comparison(
        algorithms={
            "Greedy":              greedy_nearest_neighbor,
            "Simulated Annealing": simulated_annealing,
            "Genetic Algorithm":   genetic_algorithm,
            "Memetic Algorithm":   genetic_algorithm,
            "ACO":                 ant_colony_optimization,
        },
        data=data,
        ev_params=ev_params,
        weights=weights,
        seeds=SEEDS,
        max_evaluations=MAX_EVALS,
        verbose=True,
        algorithm_kwargs={
            "Greedy":              {},
            "Simulated Annealing": sa_kwargs,
            "Genetic Algorithm":   ga_kwargs,
            "Memetic Algorithm":   ma_kwargs,
            "ACO":                 aco_kwargs,
        },
    )

    greedy_results, sa_results, ga_results, ma_results, aco_results = all_results

    print()
    print_comparison_table(all_results)
    print()
    print_detailed_metrics(all_results)
    print()
    print_summary_table(all_results)

    wilcoxon_tests = pairwise_wilcoxon(all_results)
    print_wilcoxon_table(wilcoxon_tests)

    print("LaTeX table:")
    print(to_latex_table(all_results))
    print()

    # ------------------------------------------------------------------
    # Figures
    # ------------------------------------------------------------------
    print("Saving figures …")

    # 1. Per-algorithm convergence by step (not applicable to greedy)
    for res, tag in [(sa_results, "sa"), (ga_results, "ga"), (ma_results, "ma"), (aco_results, "aco")]:
        plot_convergence(
            res,
            title=f"{res.algorithm_name} — Convergence (10 seeds)",
            save_path=FIGURES_DIR / f"{tag}_convergence_by_step.png",
            show=False,
        )

    # 2. Convergence by evaluations — fair cross-algorithm comparison (excludes greedy)
    plot_convergence_by_evaluations(
        [sa_results, ga_results, ma_results, aco_results],
        title=f"Convergence by objective evaluations (budget = {MAX_EVALS:,})",
        save_path=FIGURES_DIR / "convergence_by_evaluations.png",
        show=False,
    )

    # 3. Box plots — all algorithms including greedy baseline
    plot_box_comparison(
        all_results,
        title=f"Solution quality distribution — {len(SEEDS)} seeds, budget={MAX_EVALS:,} evals",
        save_path=FIGURES_DIR / "box_comparison.png",
        show=False,
    )

    # 4. SA diagnostics
    plot_sa_diagnostics(
        sa_results,
        seed_idx=sa_results.best_run_index,
        title=f"SA diagnostics — best seed ({sa_results.best_seed})",
        save_path=FIGURES_DIR / "sa_diagnostics.png",
        show=False,
    )

    # 5. GA diagnostics
    plot_ga_diagnostics(
        ga_results,
        seed_idx=ga_results.best_run_index,
        title=f"GA diagnostics — best seed ({ga_results.best_seed})",
        save_path=FIGURES_DIR / "ga_diagnostics.png",
        show=False,
    )

    # 6. MA diagnostics
    plot_ga_diagnostics(
        ma_results,
        seed_idx=ma_results.best_run_index,
        title=f"MA diagnostics — best seed ({ma_results.best_seed})",
        save_path=FIGURES_DIR / "ma_diagnostics.png",
        show=False,
    )

    # 7. ACO diagnostics
    plot_aco_diagnostics(
        aco_results,
        seed_idx=aco_results.best_run_index,
        title=f"ACO diagnostics — best seed ({aco_results.best_seed})",
        save_path=FIGURES_DIR / "aco_diagnostics.png",
        show=False,
    )

    # 8. Cost component breakdown
    plot_cost_breakdown(
        all_results,
        title="Cost component breakdown (best solution per algorithm)",
        save_path=FIGURES_DIR / "cost_breakdown.png",
        show=False,
    )

    # 9. Runtime comparison — wall-clock vs CPU time
    plot_runtime_comparison(
        all_results,
        title=f"Runtime comparison — {len(SEEDS)} seeds, budget={MAX_EVALS:,} evals",
        save_path=FIGURES_DIR / "runtime_comparison.png",
        show=False,
    )

    print()
    print(f"All figures saved to {FIGURES_DIR}/")
    print(f"Greedy best:              {greedy_results.best_solution}")
    print(f"SA  best (seed {sa_results.best_seed}):  {sa_results.best_solution}")
    print(f"GA  best (seed {ga_results.best_seed}):  {ga_results.best_solution}")
    print(f"MA  best (seed {ma_results.best_seed}):  {ma_results.best_solution}")
    print(f"ACO best (seed {aco_results.best_seed}): {aco_results.best_solution}")


if __name__ == "__main__":
    main()
